app:
  secret-key: 06E77CA28C2C87443C267175D0292B0CA902CAD102DB28FF48FA9DF6E88C0CB5

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:gestion-usuarios
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  error:
    include-binding-errors: always
    include-message: always